import { createApp } from "vue";
import App from "./App.vue";
// CSS vars + renderer styles only (utilities generated by Tailwind via style.css)
import "@barddev/honeycomb-vue/base.css";
import "./style.css";

createApp(App).mount("#app");
