import type { Metadata } from "next";
import { HiveProvider } from "@barddev/honeycomb-react";
// CSS vars + renderer styles only (utilities generated by Tailwind via globals.css)
import "@barddev/honeycomb-react/base.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Honeycomb React Demo",
  description: "Minimal demo of @barddev/honeycomb-react HiveProvider",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen antialiased bg-hive-background text-hive-foreground">
        <HiveProvider>{children}</HiveProvider>
      </body>
    </html>
  );
}
