import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["src/index.ts"],
    format: ["esm", "cjs"],
    dts: { resolve: ["@kkocot/honeycomb-core", "@kkocot/honeycomb-renderer"] },
    clean: false,
    splitting: false,
    sourcemap: true,
    external: [
      "react",
      "react-dom",
      "@hiveio/wax",
      "@radix-ui/react-dialog",
      "@radix-ui/react-popover",
      "@radix-ui/react-switch",
      "lucide-react",
      "@xmldom/xmldom",
      "clsx",
      "remarkable",
      "sanitize-html",
      "tailwind-merge",
      "zod",
      "@codemirror/view",
      "@codemirror/state",
      "@codemirror/lang-markdown",
      "@codemirror/language-data",
      "@codemirror/commands",
      "@codemirror/search",
      "@codemirror/theme-one-dark",
      "@codemirror/autocomplete",
    ],
    noExternal: ["@kkocot/honeycomb-core", "@kkocot/honeycomb-renderer"],
    banner: { js: '"use client";' },
  },
  {
    entry: { "vite-plugins": "src/vite-plugins.ts" },
    outDir: "dist",
    format: ["esm"],
    dts: true,
    clean: false,
    target: "esnext",
    platform: "node",
  },
]);
